# Generated by Django 5.2.8 on 2025-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0004_pedidikan_penulis_instagram_penulis_jk_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Pedidikan", new_name="Pendidikan",),
        migrations.AlterField(
            model_name="penulis",
            name="jk",
            field=models.CharField(
                blank=True,
                choices=[("PRIA", "PRIA"), ("WANITA", "WANITA")],
                max_length=50,
                null=True,
                verbose_name="Jenis Kelamin",
            ),
        ),
    ]
