# Generated by Django 5.2.8 on 2025-11-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0007_sekolah"),
    ]

    operations = [
        migrations.AddField(
            model_name="historypendidikan",
            name="sekolah",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="perpustakaan.sekolah",
                verbose_name="Sekolah",
            ),
        ),
    ]
