# Generated by Django 5.2.8 on 2025-11-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0008_historypendidikan_sekolah"),
    ]

    operations = [
        migrations.AddField(
            model_name="penulis",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="foto_penulis"),
        ),
    ]
