# Generated by Django 5.2.8 on 2025-11-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0009_penulis_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="buku",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="foto_buku"),
        ),
    ]
