# Generated by Django 5.2.8 on 2025-11-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0012_sumberdayamanusia_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devisiID", models.CharField(max_length=50, verbose_name="Devisi ID")),
                ("devisi", models.CharField(max_length=50, verbose_name="Devisi")),
                (
                    "namasingkatan",
                    models.CharField(max_length=50, verbose_name="Singkatan"),
                ),
            ],
        ),
    ]
