# Generated by Django 5.2.8 on 2025-11-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0013_devisi"),
    ]

    operations = [
        migrations.AddField(
            model_name="sumberdayamanusia",
            name="devisi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="perpustakaan.devisi",
                verbose_name="Devisi",
            ),
        ),
    ]
