# Generated by Django 5.2.8 on 2025-12-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0015_pembelianbuku_buku_created_at_buku_update_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pembelianbuku",
            name="harga",
            field=models.FloatField(max_length=250, verbose_name="Harga"),
        ),
        migrations.AlterField(
            model_name="pembelianbuku",
            name="kuantitas",
            field=models.IntegerField(max_length=250, verbose_name="Kuantitas"),
        ),
    ]
