# Generated by Django 5.2.8 on 2025-12-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0016_alter_pembelianbuku_harga_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pembelianbuku", old_name="judul", new_name="judul1",
        ),
    ]
