# Generated by Django 5.2.8 on 2025-12-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0002_peminjamanbuku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peminjamanbuku",
            name="tanggal_pengembalian",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tanggal Pengembalian"
            ),
        ),
    ]
