# Generated by Django 5.2.8 on 2025-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0002_penulis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penebit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "penebitId",
                    models.CharField(max_length=50, verbose_name="Penulis ID"),
                ),
                (
                    "namapenebit",
                    models.CharField(max_length=250, verbose_name="Nama Penulis"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="buku",
            name="sinopsi",
            field=models.TextField(verbose_name="Sinopsis"),
        ),
    ]
