# Generated by Django 5.2.8 on 2025-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0003_alter_peminjamanbuku_tanggal_pengembalian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peminjamanbuku",
            name="jumlah_buku",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Jumlah Buku"
            ),
        ),
    ]
