# Generated by Django 5.2.8 on 2025-12-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0004_alter_peminjamanbuku_jumlah_buku"),
    ]

    operations = [
        migrations.AddField(
            model_name="buku",
            name="stok",
            field=models.IntegerField(blank=True, null=True, verbose_name="Stok Buku"),
        ),
    ]
