# Generated by Django 5.2.8 on 2025-11-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0005_rename_pedidikan_pendidikan_alter_penulis_jk"),
    ]

    operations = [
        migrations.RemoveField(model_name="penulis", name="pendidikan",),
        migrations.CreateModel(
            name="HistoryPendidikan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pendidikan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perpustakaan.pendidikan",
                        verbose_name="Pendidikan",
                    ),
                ),
                (
                    "penulis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perpustakaan.penulis",
                        verbose_name="Penulis",
                    ),
                ),
            ],
        ),
    ]
