# Generated by Django 5.2.8 on 2025-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0006_remove_penulis_pendidikan_historypendidikan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sekolah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sekolahId",
                    models.CharField(max_length=50, verbose_name="Sekolah ID"),
                ),
                (
                    "namasekolah",
                    models.CharField(max_length=50, verbose_name="Nama Sekolah"),
                ),
            ],
        ),
    ]
