# Generated by Django 5.2.8 on 2025-11-26 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0010_buku_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="SumberDayaManusia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nik",
                    models.CharField(
                        max_length=50, verbose_name="No. Induk Kepegawaian"
                    ),
                ),
                ("nama", models.CharField(max_length=200, verbose_name="Nama Lengkap")),
                (
                    "jk",
                    models.CharField(
                        blank=True,
                        choices=[("PRIA", "PRIA"), ("WANITA", "WANITA")],
                        max_length=50,
                        null=True,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                ("nohp", models.CharField(max_length=50, verbose_name="No. Hp")),
                ("tgllahir", models.DateField(verbose_name="Tanggal Lahir")),
                (
                    "tempatlahir",
                    models.CharField(max_length=200, verbose_name="Tempat Lahir"),
                ),
                ("alamat", models.TextField(verbose_name="Alamat")),
                (
                    "pendidikan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perpustakaan.pendidikan",
                        verbose_name="Pendidikan",
                    ),
                ),
            ],
        ),
    ]
