# Generated by Django 5.2.8 on 2025-11-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0011_sumberdayamanusia"),
    ]

    operations = [
        migrations.AddField(
            model_name="sumberdayamanusia",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="foto_penulis"),
        ),
    ]
