# Generated by Django 5.2.8 on 2025-11-26 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0014_sumberdayamanusia_devisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="PembelianBuku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pembelianbukuId",
                    models.CharField(max_length=50, verbose_name="Buku ID"),
                ),
                ("judul", models.CharField(max_length=250, verbose_name="Judul")),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "tahunTerbit",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Tahun Terbit",
                    ),
                ),
                ("sinopsi", models.TextField(verbose_name="Sinopsis")),
                (
                    "kuantitas",
                    models.CharField(max_length=250, verbose_name="Kuantitas"),
                ),
                ("harga", models.CharField(max_length=250, verbose_name="Harga")),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="foto_buku"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="buku",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buku",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="devisi",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="devisi",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="historypendidikan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historypendidikan",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pendidikan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pendidikan",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="penebit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="penebit",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="penulis",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="penulis",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sekolah",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sekolah",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sumberdayamanusia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sumberdayamanusia",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
