# Generated by Django 5.2.8 on 2025-12-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0017_rename_judul_pembelianbuku_judul1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pembelianbuku", old_name="judul1", new_name="judul",
        ),
    ]
