# Generated by Django 5.2.8 on 2025-12-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perpustakaan", "0018_rename_judul1_pembelianbuku_judul"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pembelianbuku",
            name="pembelianbukuId",
            field=models.CharField(max_length=50, verbose_name="Pembelian Buku ID"),
        ),
    ]
